# Generated by Django 4.2.5 on 2023-09-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='last_viewed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата последнего просмотра'),
        ),
    ]
